import i18n from '../locale/i18n'
import { CONST_VALIDATOR } from '../config'
const [_, i18nObj] = i18n(false)

export const TEXT_NOTIFICATION_FAILED = {
  CANNOT_REGISTER_CONTEST: i18nObj.__('CANNOT_REGISTER_CONTEST'),
}

export const TEXT_VALIDATOR = {
  ERROR_FORBIDDEN: i18nObj.__('ERROR_FORBIDDEN'),
  INVALID_PAYLOAD: i18nObj.__('INVALID_PAYLOAD'),
  INVALID_LOGIN_CREDENTIALS: i18nObj.__('INVALID_LOGIN_CREDENTIALS'),
  ACCOUNT_IS_INACTIVE: i18nObj.__('ACCOUNT_IS_INACTIVE'),
  ACCOUNT_IS_ACTIVE: i18nObj.__('ACCOUNT_IS_ACTIVE'),
  ACCOUNT_HAD_BEEN_ACTIVATED: i18nObj.__('ACCOUNT_HAD_BEEN_ACTIVATED'),
  USERNAME_EXIST: i18nObj.__('USERNAME_EXIST'),
  EMAIL_EXIST: i18nObj.__('EMAIL_EXIST'),
  INVALID_EMAIL_FORMAT: i18nObj.__('INVALID_EMAIL_FORMAT'),
  PASSWORD_UNMATCHED: i18nObj.__('PASSWORD_UNMATCHED'),
  PASSWORD_AT_LEAST_8_LENGTH: i18nObj.__('PASSWORD_AT_LEAST_8_LENGTH'),
  PASSWORD_AT_LEAST_1_UPPER_CASE: i18nObj.__('PASSWORD_AT_LEAST_1_UPPER_CASE'),
  PASSWORD_AT_LEAST_1_NUMBER: i18nObj.__('PASSWORD_AT_LEAST_1_NUMBER'),
  PASSWORD_AT_LEAST_1_SPECIAL_CHAR: i18nObj.__('PASSWORD_AT_LEAST_1_SPECIAL_CHAR'),
  PASSWORD_MAY_NOT_CONTAIN_SEQUENCES: i18nObj.__('PASSWORD_MAY_NOT_CONTAIN_SEQUENCES'),
  USER_INFO_MUST_IN_RANGE: i18nObj.__('LENGTH_MUST_IN_RANGE_{{MIN}}_{{MAX}}', {MIN: CONST_VALIDATOR.USER_INFO_MIN_LENGTH, MAX: CONST_VALIDATOR.USER_INFO_MAX_LENGTH }),
  ACTIVATE_TOKEN_EXPIRED: i18nObj.__('ACTIVATE_TOKEN_EXPIRED'),
  ACTIVATE_TOKEN_INVALID: i18nObj.__('ACTIVATE_TOKEN_INVALID'),
  INVALID_OLD_PASSWORD: i18nObj.__('INVALID_OLD_PASSWORD'),
  NEWS_COMMENT_MUST_IN_RANGE: i18nObj.__('LENGTH_AT_LEAST_{{MIN}}', {MIN: CONST_VALIDATOR.NEWS_COMMENT_MIN_LENGTH}),
  LOCALE_NOT_FOUND: i18nObj.__('LOCALE_NOT_FOUND'),
  TEAM_MEMBER_EXISTED: i18nObj.__('TEAM_MEMBER_EXISTED'),
  TEAM_NAME_EXISTED: i18nObj.__('TEAM_NAME_EXISTED'),
  CANNOT_FIND_USER: i18nObj.__('CANNOT_FIND_USER'),
  CANNOT_FIND_TEAM: i18nObj.__('CANNOT_FIND_TEAM'),
  CANNOT_FIND_CONTEST: i18nObj.__('CANNOT_FIND_CONTEST'),
  CANNOT_FIND_ONGOING_CONTEST_ROOM: i18nObj.__('CANNOT_FIND_ONGOING_CONTEST_ROOM'),
}

export const TEXT_NOTIFICATION_ERROR = {
  'jwt-expired': TEXT_VALIDATOR.ACTIVATE_TOKEN_EXPIRED,
  'invalid-token': TEXT_VALIDATOR.ACTIVATE_TOKEN_INVALID,
  'invalid-signature': TEXT_VALIDATOR.ACTIVATE_TOKEN_INVALID,
}
